doc: add design document for Cluster vs Namespace
bpfman/bpfman pull request #1359
Opened 2024-12-11 21:27 UTC by Billy99

Add a design document for Cluster vs Namespace Scoped CRDs in bpfman.

2025-01-02 20:39 UTC, anfredette requested changes
I made a few minor suggestions, but looks good to me otherwise.  Thanks!

2025-01-02 20:39 UTC, anfredette commented on docs/design/clusterVsNamespaceScoped.md
> +So looks something like this:
```suggestion
## Adding Namespaced Scoped CRDs
```

2025-01-02 20:39 UTC, anfredette commented on docs/design/clusterVsNamespaceScoped.md
> +                     |     func (r *FentryProgramReconciler) getFinalizer() string {}
```suggestion
While the contents are the same for the namespace and cluster-scoped CRD in most cases, Kubernetes requires different 
CRD for each type.
```

2025-01-02 20:39 UTC, anfredette commented on docs/design/clusterVsNamespaceScoped.md
> +type TcNsProgramList struct {
```suggestion
To allow the common code to act on both Cluster or Namespaced objects, two new interfaces will be introduced.
```

2025-01-02 20:39 UTC, anfredette commented on docs/design/clusterVsNamespaceScoped.md
> +* FentryProgram
```suggestion
Around the same time this feature is being developed, another feature is being developed
```

2025-01-02 20:39 UTC, anfredette commented on docs/design/clusterVsNamespaceScoped.md
> +for namespaced objects to not have an identifier.
```suggestion
carry the identifier.  After the load/attach split work is complete, the CRDs will be renamed to follow the common convention in which the cluster-scoped CRD names are prefixed with "Cluster".
```

We may not do a v1alpha2 now.

2025-01-02 21:27 UTC, Billy99 reviewed
Your comment lines were off, so the suggested diff was off as well. I think I figured out what your intent was, but I add what I changed to verify that was your intent.

2025-01-02 21:27 UTC, Billy99 commented on docs/design/clusterVsNamespaceScoped.md
> +
Done (added `s` to content).

2025-01-02 21:27 UTC, Billy99 commented on docs/design/clusterVsNamespaceScoped.md
> +:
Done (removed `in` from in front of `each`).

2025-01-02 21:27 UTC, Billy99 commented on docs/design/clusterVsNamespaceScoped.md
> +So looks something like this:
Done (added `CRDs`)

2025-01-02 21:27 UTC, Billy99 commented on docs/design/clusterVsNamespaceScoped.md
> +                     |     func (r *FentryProgramReconciler) getFinalizer() string {}
Done (replaced `To add Namespace scoped BPF Program and \*Program CRDs, Kubernetes requires new CRDs for each type.` with your text. Did add the word `mostly` the same, since we had to remove namespace from ContainerSelector.)

2025-01-02 21:27 UTC, Billy99 commented on docs/design/clusterVsNamespaceScoped.md
> +type TcNsProgramList struct {
Done (added `d` to `introduce`.)

2025-01-02 21:27 UTC, Billy99 commented on docs/design/clusterVsNamespaceScoped.md
> +* FentryProgram
Done (removed `r` from `featurer`)

2025-01-02 21:27 UTC, Billy99 commented on docs/design/clusterVsNamespaceScoped.md
> +for namespaced objects to not have an identifier.
Done

2025-01-03 14:25 UTC, anfredette commented on docs/getting-started/operator-quick-start.md
> +The script defaults these fields to what is current in
```suggestion
The script defaults these fields to what is currently in 
```

2025-01-03 14:36 UTC, anfredette commented on docs/getting-started/operator-quick-start.md
> +back to the user via the `tcNsProgram`'s status field:
I think it would be better to say how it works in general, and then use TC as an example.

```suggestion
The status for each namespaced program is reported via the \*NsProgram status field and further information
can be seen in the resulting BpfNsProgram CRDs.  As an example, the following commands display the information 
of the TC program loaded in the acme namespace with the command above.
```

2025-01-03 14:43 UTC, anfredette commented on docs/getting-started/operator-quick-start.md
> +### Cluster Scoped Versus Namespaced Scoped CRDs
It seems like this info would be useful before we go through the cluster and namespace examples above.

2025-01-03 14:58 UTC, anfredette commented
> Your comment lines were off

Sorry about that.  I may not have refreshed things correctly after your last update.

2025-01-03 15:19 UTC, Billy99 reviewed
Done

2025-01-03 15:19 UTC, Billy99 commented on docs/getting-started/operator-quick-start.md
> +The script defaults these fields to what is current in
Done.

2025-01-03 15:19 UTC, Billy99 commented on docs/getting-started/operator-quick-start.md
> +A yaml has been created that will create a `Namespace`
Done.

2025-01-03 15:19 UTC, Billy99 commented on docs/getting-started/operator-quick-start.md
> +back to the user via the `tcNsProgram`'s status field:
Done.

2025-01-03 15:19 UTC, Billy99 commented on docs/getting-started/operator-quick-start.md
> +### Cluster Scoped Versus Namespaced Scoped CRDs
I moved the entire `## API Types Overview` section up, after bpfman-operator and bpfman-daemon have been deployed and verified, but before any of the samples have been run.

2025-01-03 15:26 UTC, anfredette approved these changes
/LGTM

2025-01-03 15:54 UTC, merged