bpf: adds cleanup for tc programs when qdisc is deleted
bpfman/bpfman pull request #759
Opened 2023-10-04 23:12 UTC by navarrothiago

Closes: #468

[![asciicast](https://asciinema.org/a/611968.svg)](https://asciinema.org/a/611968)

2023-10-05 02:52 UTC, navarrothiago commented
Still need to fix the jobs...

2023-10-11 18:50 UTC, anfredette commented
@navarrothiago thanks for submitting this.  I've taken a quick look at the code and have tried it out.  I think this is a really good function to have.  This could be a separate PR, but if we could also trigger the operator to do a reconcile for TC programs after your code does the cleanup, the bpfd programs would get reinstalled.  I'm also wondering if we could/should do something similar for XDP.  I.e., if someone replaces our XDP dispatcher on an interface, we could clean up the XDP state too.

I'd like to do a more thorough review of the code and would also like to discuss the approach in the community meeting tomorrow to get feedback from others.

I'm going to put a hold on it for now pending that feedback.

2023-10-12 19:57 UTC, anfredette requested changes
As discussed, rather than install our own bpf tracepoint program, we should be able to get this information via netlink notifications.  Furthermore, it would be beneficial, in general, for bpfd to have a way to subscribe to arbitrary notifications that we may care about for other reasons.  For example, the case where the xdp_dispatcher is removed that I mentioned earlier.  Please take a look at the same netlink library that was suggested in pr #761.

Additionally, rather than cleaning everything up, I think we can rebuild and reattach a new dispatcher.  What happens when the clsact qdisc is deleted is that the tc_dispatcher becomes no longer attached, so the user bpf programs are no longer being executed.  However, all of the programs are still loaded in memory and bpfd state reflects what we'd like to be the case.  So, we should be able to do something very similar to what is being done in [rebuild_dispatcher_state()](https://github.com/bpfd-dev/bpfd/blob/main/bpfd/src/bpf.rs#L212).

It's a little different because rather than looping through the dispatcher directory entries like we're currently doing, for this case we'd look in the dispatcher directory to see if we have an ingress and/or egress dispatcher for the particular interface on which the qdisc was just deleted.  If we do, then we rebuild just those.  Also, we shouldn't need to call [self.dispatchers.insert()](https://github.com/bpfd-dev/bpfd/blob/main/bpfd/src/bpf.rs#L241C21-L241C45) because it's already on the list.

2023-10-12 20:08 UTC, anfredette commented
> look in the dispatcher directory to see if we have an ingress and/or egress dispatcher for the particular interface on which the qdisc was just deleted

Actually, rather than looking in the directory, we could just check if the dispatcher exists in our [dispatcher map](https://github.com/bpfd-dev/bpfd/blob/main/bpfd/src/bpf.rs#L50).

2024-04-28 14:39 UTC, anfredette commented
@navarrothiago, this has been inactive for a while now.  Unless I hear from you otherwise, I'm planning to close it.  Thanks, Andre

2024-05-03 13:00 UTC, anfredette commented
Closing pr because it has not been updated for a long time.

@navarrothiago we appreciate your contribution and welcome you to update this in the future.

2024-05-03 13:00 UTC, closed without merging